require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = ["--format documentation", "--color", "--order=default"]
  t.pattern = "spec/{deck,pile,ai_player}_spec.rb"
  t.pattern = ARGV[1] if ARGV.count > 1
end

task :default => :spec
